routes/web.php
<?php

use App\Http\Controllers\ApiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GroupController;
use App\Http\Middleware\CheckAdminMiddleware;
use App\Http\Middleware\CheckLoginMiddleware;
use Illuminate\Support\Facades\Route;

Route::get('/', static function() {
    return redirect()->route('login');
});
Route::get('/login', [AuthController::class, 'loginView'])->name('login_view');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::group([
    'prefix' => 'api',
    'as' => 'api.',
    'middleware' => CheckLoginMiddleware::class
], static function() {
    Route::get('/', [ApiController::class, 'index'])->name('index');

    Route::group(['middleware' => CheckAdminMiddleware::class], static function() {
        Route::get('/create', [ApiController::class, 'create'])->name('create');
        Route::post('/store', [ApiController::class, 'store'])->name('store');
        Route::get('/edit/{api}', [ApiController::class, 'edit'])->name('edit');
        Route::put('/update/{api}', [ApiController::class, 'update'])->name('update');
    });

});


Route::get('/group', [GroupController::class, 'index'])->name('group');

resources/views/create.blade.php
@extends('layout.master')

@section('content')
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                    <li class="breadcrumb-item active">Thêm API</li>
                </ol>
            </div>
            <h4 class="page-title">Starter</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<!-- START MY CODE -->
<form action="{{route('api.store')}}" method="post">
    @csrf
<div class="form-group">
    <label>Tên nhóm</label>
    <br>
    Thêm nhóm mới
    <input type="checkbox" id="toggle_group_name" data-switch="none"/>
    <label for="toggle_group_name" data-on-label="" data-off-label=""></label>

    <div>
    <select id="group_name_2" name="group_name" class="form-control select2" data-toggle="select2">
        @foreach($group_names as $group_name)
            <option value="{{$group_name}}">{{$group_name}}</option>
        @endforeach
    </select>
    </div>

    <input type="text" id="group_name_1" class="form-control" hidden placeholder="Nhóm Users" name="group_name">

</div>

<div class="mt-2">
    <label>Phương thức</label>
    <br>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" id="customRadio1" name="type_name" class="custom-control-input" value="get">
        <label class="custom-control-label" for="customRadio1">GET</label>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" id="customRadio2" name="type_name" class="custom-control-input" value="post">
        <label class="custom-control-label" for="customRadio2">POST</label>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" id="customRadio3" name="type_name" class="custom-control-input" value="put">
        <label class="custom-control-label" for="customRadio3">PUT</label>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" id="customRadio4" name="type_name" class="custom-control-input" value="delete">
        <label class="custom-control-label" for="customRadio4">DELETE</label>
    </div>
</div>

<br>

<div class="form-group">
    <label for="example-palaceholder">URL</label>
    <input type="text" id="example-palaceholder" class="form-control" placeholder="/api/app/student/{id:mã của học sinh}" name="url">
</div>

<div class="form-group">
    <label for="example-palaceholder">Mô tả về API</label>
    <input type="text" id="example-palaceholder" class="form-control" placeholder="trả về chi tiết 1 học sinh" name="api_name">
</div>

<div class="form-group">
    <label for="example-textarea">Header</label>
    <textarea class="form-control" id="example-textarea" rows="2" placeholder="Authorization:Bearer: {token}
Content-Type:application/json" name="header"></textarea>
</div>

<div class="form-group">
    <label for="example-textarea">Body</label>
    <textarea class="form-control" id="example-textarea" rows="5" placeholder="username:string:tên tài khoản
password:string:mật khẩu
name:string:tên của người dùng" name="body"></textarea>
</div>

<div class="form-group">
    <label for="example-textarea">Dữ liệu mẫu cho body</label>
    <textarea class="form-control" id="example-textarea" rows="3" placeholder="{&quot;id&quot;:0,&quot;category&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;},&quot;name&quot;:&quot;doggie&quot;,&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}" name="sample_body"></textarea>
</div>

<div class="form-group">
    <label for="example-textarea">Response</label>
    <textarea class="form-control" id="example-textarea" rows="5" placeholder="username:string:tên tài khoản
password:string:mật khẩu
name:string:tên của người dùng" name="response"></textarea>
</div>

<div class="form-group">
    <label for="example-textarea">Dữ liệu mẫu cho response</label>
    <textarea class="form-control" id="example-textarea" rows="3" placeholder="{&quot;id&quot;:0,&quot;category&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;},&quot;name&quot;:&quot;doggie&quot;,&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}" name="sample_response"></textarea>
</div>


<div class="form-group">
    <label for="example-textarea">Note</label>
    <textarea class="form-control" rows="3" placeholder="không có note" name="note" id="myeditorinstance">Hello, World!</textarea>
</div>

<!--  <div class="form-group">
     <label for="example-select">Vị trí</label>
     <select class="form-control" id="example-select">
         <option>Trên cùng</option>
         <option>Sau API Lấy ra toàn bộ sinh viên</option>
         <option>Sau API lấy toàn bộ sinh viên</option>
         <option>Sau API cập nhật sinh viên</option>
         <option>Cuối cùng</option>
     </select>
 </div> -->
<button id="submit" class="btn btn-warning"><i class="mdi mdi-rocket mr-1"></i> <span>Launch</span> </button>

<!-- END MY CODE -->

</form>
@endsection

@section('more_script')
    <script>
        $(document).ready(function() {
            let toggle = $('#toggle_group_name')
            toggle.on('click', function () {
                if (toggle.is(":checked")) {
                    $('#group_name_2').parent().hide()
                    $('#group_name_1').removeAttr('hidden');
                } else {
                    $('#group_name_1').attr('hidden', true);
                    $('#group_name_2').parent().show()
                }
            })

            let button = $('#submit')
            button.on('click', function () {
                if (toggle.is(":checked")) {
                    $('#group_name_2').removeAttr('name')
                } else {
                    $('#group_name_1').removeAttr('name')
                }

            })
        })
    </script>
    <script src="https://cdn.tiny.cloud/1/free/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#myeditorinstance',
            content_css: 'tinymce-5-dark',
            skin: 'oxide-dark',
            height: 270,
            plugins: 'advcode table checklist image advlist autolink lists link charmap preview codesample imagetool fullscreen',
            toolbar: 'insertfile | blocks| bold italic | fullscreen | image | link | preview | codesample | bullist numlist checklist |  alignleft aligncenter alignright',
            menubar: 'insert view',
            mobile: {
                menubar: true
            },
            setup: function(editor) {
                editor.on('init', function (e) {
                    setTimeout(function() {
                        $("button[tabindex='-1'].tox-notification__dismiss.tox-button.tox-button--naked.tox-button--icon")[0].click()
                    }, 10);

                })
            },
            file_picker_types: 'image',
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input')
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*')
                input.onchange = function () {
                    var file = this.files[0];
                    var reader = new FileReader()
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime()
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache
                        var base64 = reader.result.split(',')[1]
                        var blobInfo = blobCache.create(id, file, base64)
                        blobCache.add(blobInfo)
                        cb(blobInfo.blobUri(), { title: file.name })
                    }
                    reader.readAsDataURL(file)
                }
                input.click()
            },
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });
    </script>
@endsection

resources/views/edit.blade.php
@extends('layout.master')

@section('content')
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">Thêm API</li>
                    </ol>
                </div>
                <h4 class="page-title">Starter</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <!-- START MY CODE -->
    <form id="main_form" action="{{route('api.update', ['api' => $data->id])}}" method="post">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label>Tên nhóm</label>
            <br>
            Thêm nhóm mới
            <input type="checkbox" id="toggle_group_name" data-switch="none"/>
            <label for="toggle_group_name" data-on-label="" data-off-label=""></label>

            <div>
                <select id="group_name_2" name="group_name" class="form-control select2" data-toggle="select2">
                    @foreach($group_names as $key => $group_name)
                        <option value="{{$group_name}}"
                            @if($group_name === $data->group->name) selected @endif
                        >
                            {{$group_name}}
                        </option>
                    @endforeach
                </select>
            </div>

            <input type="text" id="group_name_1" class="form-control" hidden placeholder="Nhóm Users" name="group_name">

        </div>

        <div class="mt-2">
            <label>Phương thức</label>
            <br>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="customRadio1" name="type_name" class="custom-control-input" value="get" @if ($data->method->name === 'get') checked @endif>
                <label class="custom-control-label" for="customRadio1">GET</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="customRadio2" name="type_name" class="custom-control-input" value="post" @if ($data->method->name === 'post') checked @endif>
                <label class="custom-control-label" for="customRadio2">POST</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="customRadio3" name="type_name" class="custom-control-input" value="put" @if ($data->method->name === 'put') checked @endif>
                <label class="custom-control-label" for="customRadio3">PUT</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="customRadio4" name="type_name" class="custom-control-input" value="delete" @if ($data->method->name === 'delete') checked @endif>
                <label class="custom-control-label" for="customRadio4">DELETE</label>
            </div>
        </div>

        <br>

        <div class="form-group">
            <label for="example-palaceholder">URL</label>
            <input value="{{$data->method->url}}" type="text" id="example-palaceholder" class="form-control" placeholder="/api/app/student/{id:mã của học sinh}" name="url">
        </div>

        <div class="form-group">
            <label for="example-palaceholder">Mô tả về API</label>
            <input value="{{$data->name}}" type="text" id="example-palaceholder" class="form-control" placeholder="trả về chi tiết 1 học sinh" name="api_name">
        </div>

        <div class="form-group">
            <label for="example-textarea">Header</label>
            <textarea class="form-control" id="example-textarea" rows="2" placeholder="Authorization:Bearer: {token}
Content-Type:application/json" name="header">@foreach($data->method->headers as $header){{$header->key}}:{{$header->value}}
@endforeach</textarea>
        </div>

        <div class="form-group">
            <label for="example-textarea">Body</label>
            <textarea class="form-control" id="example-textarea" rows="5" placeholder="username:string:tên tài khoản
password:string:mật khẩu
name:string:tên của người dùng" name="body">@foreach($data->method->bodies as $body){{$body->field}}:{{$body->data_type}}:{{$body->description}}
@endforeach</textarea>
        </div>

        <div class="form-group">
            <label for="example-textarea">Dữ liệu mẫu cho body</label>
            <textarea class="form-control" id="example-textarea" rows="3" placeholder="{&quot;id&quot;:0,&quot;category&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;},&quot;name&quot;:&quot;doggie&quot;,&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}" name="sample_body">{{$data->method->sample_body}}</textarea>
        </div>

        <div class="form-group">
            <label for="example-textarea">Response</label>
            <textarea class="form-control" id="example-textarea" rows="5" placeholder="username:string:tên tài khoản
password:string:mật khẩu
name:string:tên của người dùng" name="response">@foreach($data->method->responses as $response){{$response->field}}:{{$response->data_type}}:{{$response->description}}
@endforeach</textarea>
        </div>

        <div class="form-group">
            <label for="example-textarea">Dữ liệu mẫu cho response</label>
            <textarea class="form-control" id="example-textarea" rows="3" placeholder="{&quot;id&quot;:0,&quot;category&quot;:{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;},&quot;name&quot;:&quot;doggie&quot;,&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}" name="sample_response">{{$data->method->sample_response}}</textarea>
        </div>


        <div class="form-group">
            <label for="example-textarea">Note</label>
            <textarea class="form-control" rows="3" placeholder="không có note" name="note" id="myeditorinstance">{{$data->method->note}}</textarea>
        </div>

        <!--  <div class="form-group">
             <label for="example-select">Vị trí</label>
             <select class="form-control" id="example-select">
                 <option>Trên cùng</option>
                 <option>Sau API Lấy ra toàn bộ sinh viên</option>
                 <option>Sau API lấy toàn bộ sinh viên</option>
                 <option>Sau API cập nhật sinh viên</option>
                 <option>Cuối cùng</option>
             </select>
         </div> -->
        <button class="btn btn-warning"><i class="mdi mdi-rocket mr-1"></i> <span>Launch</span> </button>

        <!-- END MY CODE -->

    </form>
@endsection

@section('more_script')
    <script>
        $(document).ready(function() {
            let toggle = $('#toggle_group_name')
            toggle.on('click', function() {
                if (toggle.is(":checked")) {
                    $('#group_name_2').parent().hide()
                    $('#group_name_1').removeAttr('hidden');
                } else {
                    $('#group_name_1').attr('hidden', true);
                    $('#group_name_2').parent().show()
                }
            })
            let form = $('#main_form')
            form.on('submit', function (e) {
                if (toggle.is(":checked")) {
                    $('#group_name_2').removeAttr('name')
                } else {
                    $('#group_name_1').removeAttr('name')
                }
            })
        })
    </script>
    <script src="https://cdn.tiny.cloud/1/free/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#myeditorinstance',
            content_css: 'tinymce-5-dark',
            skin: 'oxide-dark',
            height: 270,
            plugins: 'advcode table checklist image advlist autolink lists link charmap preview codesample imagetool fullscreen',
            toolbar: 'insertfile | blocks| bold italic | fullscreen | image | link | preview | codesample | bullist numlist checklist |  alignleft aligncenter alignright',
            menubar: 'insert view',
            mobile: {
                menubar: true
            },
            setup: function(editor) {
                editor.on('init', function (e) {
                    setTimeout(function() {
                        $("button[tabindex='-1'].tox-notification__dismiss.tox-button.tox-button--naked.tox-button--icon")[0].click()
                    }, 10);

                })
            },
            file_picker_types: 'image',
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input')
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*')
                input.onchange = function () {
                    var file = this.files[0];
                    var reader = new FileReader()
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime()
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache
                        var base64 = reader.result.split(',')[1]
                        var blobInfo = blobCache.create(id, file, base64)
                        blobCache.add(blobInfo)
                        cb(blobInfo.blobUri(), { title: file.name })
                    }
                    reader.readAsDataURL(file)
                }
                input.click()
            },
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });
    </script>
@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Api Document App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="Api Document">
    <meta itemprop="description" content="Api Document">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://api-document.maoleng.dev">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Api Document App">
    <meta property="og:image" content="{{asset('assets/img/meta-image.jpg')}}">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:title" content="Api Document App">
    <meta name="twitter:image" content="{{asset('assets/img/meta-image.jpg')}}">
    <meta name="twitter:card" content="{{asset('assets/img/meta-image.jpg')}}">

<style>
    html {
        height: 100%;
    }
    body {
        margin:0;
        padding:0;
        font-family: sans-serif;
        background: linear-gradient(#141e30, #243b55);
    }

    .login-box {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 400px;
        padding: 40px;
        transform: translate(-50%, -50%);
        background: rgba(0,0,0,.5);
        box-sizing: border-box;
        box-shadow: 0 15px 25px rgba(0,0,0,.6);
        border-radius: 10px;
    }

    .login-box h2 {
        margin: 0 0 30px;
        padding: 0;
        color: #fff;
        text-align: center;
    }

    .login-box .user-box {
        position: relative;
    }

    .login-box .user-box input {
        width: 100%;
        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        margin-bottom: 30px;
        border: none;
        border-bottom: 1px solid #fff;
        outline: none;
        background: transparent;
    }
    .login-box .user-box label {
        position: absolute;
        top:0;
        left: 0;
        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        pointer-events: none;
        transition: .5s;
    }

    .login-box .user-box input:focus ~ label,
    .login-box .user-box input:valid ~ label {
        top: -20px;
        left: 0;
        color: #03e9f4;
        font-size: 12px;
    }

    .login-box form button {
        background-color: rgba(0,0,0,.5);
        border: none;
        position: relative;
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 16px;
        text-decoration: none;
        text-transform: uppercase;
        overflow: hidden;
        transition: .5s;
        margin-top: 40px;
        letter-spacing: 4px;
    }

    .login-box button:hover {
        background: #03e9f4;
        color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 5px #03e9f4,
        0 0 25px #03e9f4,
        0 0 50px #03e9f4,
        0 0 100px #03e9f4;
        cursor: pointer;

    }

    .login-box button span {
        position: absolute;
        display: block;
    }

    .login-box button span:nth-child(1) {
        top: 0;
        left: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(90deg, transparent, #03e9f4);
        animation: btn-anim1 1s linear infinite;
    }

    @keyframes btn-anim1 {
        0% {
            left: -100%;
        }
        50%,100% {
            left: 100%;
        }
    }

    .login-box button span:nth-child(2) {
        top: -100%;
        right: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(180deg, transparent, #03e9f4);
        animation: btn-anim2 1s linear infinite;
        animation-delay: .25s
    }

    @keyframes btn-anim2 {
        0% {
            top: -100%;
        }
        50%,100% {
            top: 100%;
        }
    }

    .login-box button span:nth-child(3) {
        bottom: 0;
        right: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(270deg, transparent, #03e9f4);
        animation: btn-anim3 1s linear infinite;
        animation-delay: .5s
    }

    @keyframes btn-anim3 {
        0% {
            right: -100%;
        }
        50%,100% {
            right: 100%;
        }
    }

    .login-box button span:nth-child(4) {
        bottom: -100%;
        left: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(360deg, transparent, #03e9f4);
        animation: btn-anim4 1s linear infinite;
        animation-delay: .75s
    }

    @keyframes btn-anim4 {
        0% {
            bottom: -100%;
        }
        50%,100% {
            bottom: 100%;
        }
    }

</style>
</head>

<body>
<div class="login-box">
    <h2>Login</h2>
    <form action="{{route('login')}}" method="post">
        @csrf
        <div class="user-box">
            <input type="text" name="email">
            <label>Email</label>
        </div>
        <div class="user-box">
            <input type="password" name="password">
            <label>Password</label>
        </div>
        <button>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Login
        </button>
    </form>
</div>
</body>
</html>