routes/web.php
<?php

use App\Http\Controllers\ApiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GroupController;
use App\Http\Middleware\CheckAdminMiddleware;
use App\Http\Middleware\CheckLoginMiddleware;
use Illuminate\Support\Facades\Route;

Route::get('/', static function() {
    return redirect()->route('login');
});
Route::get('/login', [AuthController::class, 'loginView'])->name('login_view');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::group([
    'prefix' => 'api',
    'as' => 'api.',
    'middleware' => CheckLoginMiddleware::class
], static function() {
    Route::get('/', [ApiController::class, 'index'])->name('index');

    Route::group(['middleware' => CheckAdminMiddleware::class], static function() {
        Route::get('/create', [ApiController::class, 'create'])->name('create');
        Route::post('/store', [ApiController::class, 'store'])->name('store');
        Route::get('/edit/{api}', [ApiController::class, 'edit'])->name('edit');
        Route::put('/update/{api}', [ApiController::class, 'update'])->name('update');
    });

});


Route::get('/group', [GroupController::class, 'index'])->name('group');

resources/views/layout/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2022 © Api Document App - Mao Leng
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layout/header.blade.php
<!-- Topbar Start -->
<div class="navbar-custom">
    <ul class="list-unstyled topbar-right-menu float-right mb-0">
        <li class="dropdown notification-list d-lg-none">
            <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-search noti-icon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-animated dropdown-lg p-0">
                <form class="p-3">
                    <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                </form>
            </div>
        </li>


{{--        <li class="dropdown notification-list">--}}
{{--            <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button"--}}
{{--               aria-haspopup="false" aria-expanded="false">--}}
{{--                <i class="dripicons-bell noti-icon"></i>--}}
{{--                <span class="noti-icon-badge"></span>--}}
{{--            </a>--}}
{{--            <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">--}}

{{--                <!-- item-->--}}
{{--                <div class="dropdown-item noti-title">--}}
{{--                    <h5 class="m-0">--}}
{{--                                    <span class="float-right">--}}
{{--                                        <a href="javascript: void(0);" class="text-dark">--}}
{{--                                            <small>Clear All</small>--}}
{{--                                        </a>--}}
{{--                                    </span>Notification--}}
{{--                    </h5>--}}
{{--                </div>--}}

{{--                <div style="max-height: 230px;" data-simplebar>--}}
{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon bg-primary">--}}
{{--                            <i class="mdi mdi-comment-account-outline"></i>--}}
{{--                        </div>--}}
{{--                        <p class="notify-details">Caleb Flakelar commented on Admin--}}
{{--                            <small class="text-muted">1 min ago</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}

{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon bg-info">--}}
{{--                            <i class="mdi mdi-account-plus"></i>--}}
{{--                        </div>--}}
{{--                        <p class="notify-details">New user registered.--}}
{{--                            <small class="text-muted">5 hours ago</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}

{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon">--}}
{{--                            <img src="{{asset('assets/images/users/avatar-2.jpg')}}" class="img-fluid rounded-circle"--}}
{{--                                 alt=""/></div>--}}
{{--                        <p class="notify-details">Cristina Pride</p>--}}
{{--                        <p class="text-muted mb-0 user-msg">--}}
{{--                            <small>Hi, How are you? What about our next meeting</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}

{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon bg-primary">--}}
{{--                            <i class="mdi mdi-comment-account-outline"></i>--}}
{{--                        </div>--}}
{{--                        <p class="notify-details">Caleb Flakelar commented on Admin--}}
{{--                            <small class="text-muted">4 days ago</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}

{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon">--}}
{{--                            <img src="{{asset('assets/images/users/avatar-4.jpg')}}" class="img-fluid rounded-circle"--}}
{{--                                 alt=""/></div>--}}
{{--                        <p class="notify-details">Karen Robinson</p>--}}
{{--                        <p class="text-muted mb-0 user-msg">--}}
{{--                            <small>Wow ! this admin looks good and awesome design</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}

{{--                    <!-- item-->--}}
{{--                    <a href="javascript:void(0);" class="dropdown-item notify-item">--}}
{{--                        <div class="notify-icon bg-info">--}}
{{--                            <i class="mdi mdi-heart"></i>--}}
{{--                        </div>--}}
{{--                        <p class="notify-details">Carlos Crouch liked--}}
{{--                            <b>Admin</b>--}}
{{--                            <small class="text-muted">13 days ago</small>--}}
{{--                        </p>--}}
{{--                    </a>--}}
{{--                </div>--}}

{{--                <!-- All-->--}}
{{--                <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">--}}
{{--                    View All--}}
{{--                </a>--}}

{{--            </div>--}}
{{--        </li>--}}




        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <span class="account-user-avatar">
                    <img src="{{asset('assets/images/users/avatar-1.jpg')}}" alt="user-image" class="rounded-circle">
                </span>
                <span>
                    <span class="account-user-name">{{getName()}}</span>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                <!-- item-->
                <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Xin chào !</h6>
                </div>

                <!-- item-->
                <a href="{{route('logout')}}" class="dropdown-item notify-item">
                    <i class="mdi mdi-logout mr-1"></i>
                    <span>Tạm biệt</span>
                </a>

            </div>
        </li>

    </ul>
    <button class="button-menu-mobile open-left disable-btn">
        <i class="mdi mdi-menu"></i>
    </button>
    <div class="app-search dropdown d-none d-lg-block">
        <form>
            <div class="input-group">
                <input type="text" class="form-control dropdown-toggle" placeholder="Search..." id="top-search">
                <span class="mdi mdi-magnify search-icon"></span>
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>

        </form>

        <div class="dropdown-menu dropdown-menu-animated dropdown-lg" id="search-dropdown">
            <!-- item-->
            <div class="dropdown-header noti-title">
                <h5 class="text-overflow mb-2">Found <span class="text-danger">17</span> results</h5>
            </div>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-notes font-16 mr-1"></i>
                <span>Analytics Report</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-life-ring font-16 mr-1"></i>
                <span>How can I help you?</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-cog font-16 mr-1"></i>
                <span>User profile settings</span>
            </a>

            <!-- item-->
            <div class="dropdown-header noti-title">
                <h6 class="text-overflow mb-2 text-uppercase">Users</h6>
            </div>

            <div class="notification-list">
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <div class="media">
                        <img class="d-flex mr-2 rounded-circle" src="{{asset('assets/images/users/avatar-2.jpg')}}"
                             alt="Generic placeholder image" height="32">
                        <div class="media-body">
                            <h5 class="m-0 font-14">Erwin Brown</h5>
                            <span class="font-12 mb-0">UI Designer</span>
                        </div>
                    </div>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <div class="media">
                        <img class="d-flex mr-2 rounded-circle" src="{{asset('assets/images/users/avatar-5.jpg')}}"
                             alt="Generic placeholder image" height="32">
                        <div class="media-body">
                            <h5 class="m-0 font-14">Jacob Deo</h5>
                            <span class="font-12 mb-0">Developer</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- end Topbar -->

resources/views/layout/left-sidebar.blade.php
<div class="left-side-menu">

    <!-- LOGO -->
    <a href="{{route('api.index')}}" class="logo text-center logo-light">
        <span class="logo-lg">
{{--            <img src="{{asset('assets/images/logo.png')}}" alt="" height="16">--}}
            <h2>Api Document App</h2>
        </span>
        <span class="logo-sm">
{{--            <img src="{{asset('assets/images/logo_sm.png')}}" alt="" height="16">--}}
        </span>
    </a>

    <!-- LOGO -->
    <a href="{{route('api.index')}}" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="{{asset('assets/images/logo-dark.png')}}" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="{{asset('assets/images/logo_sm_dark.png')}}" alt="" height="16">
        </span>
    </a>

    <div class="h-100" id="left-side-menu-container" data-simplebar>

        <!--- Sidemenu -->
        <ul class="metismenu side-nav">

            <li class="side-nav-title side-nav-item">Phần mềm</li>

            <li class="side-nav-item">
                <a href="{{route('api.index')}}" class="side-nav-link">
                    <i class="uil-calender"></i>
                    <span> Tài liệu API </span>
                </a>
            </li>

            @if(session()->get('level') === 1)
            <li class="side-nav-title side-nav-item">Quản lý</li>

            <li class="side-nav-item">
                <a href="{{route('api.create')}}" class="side-nav-link">
                    <i class="uil-layer-group"></i>
                    <span> Thêm API </span>
                </a>
            </li>


            <li class="side-nav-item">
                <a href="https://api.github.com" class="side-nav-link">
                    <i class="uil-comments-alt"></i>
                    <span> Chat </span>
                </a>
            </li>
            @endif
        </ul>

        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Api Document App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="Api Document">
    <meta itemprop="description" content="Api Document">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://api-document.maoleng.dev">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Api Document App">
    <meta property="og:image" content="{{asset('assets/img/meta-image.jpg')}}">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:title" content="Api Document App">
    <meta name="twitter:image" content="{{asset('assets/img/meta-image.jpg')}}">
    <meta name="twitter:card" content="{{asset('assets/img/meta-image.jpg')}}">

    <meta content="App" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{asset('assets/images/favicon.ico')}}">

    <!-- App css -->
    <link href="{{asset('assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/css/app-dark.min.css')}}" rel="stylesheet" type="text/css" id="dark-style" />


    @yield('more_style')
</head>



<body class="loading" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'>

<!-- Pre-loader -->
<div id="preloader">
    <div id="status">
        <div class="bouncing-loader"><div ></div><div ></div><div ></div></div>
    </div>
</div>
<!-- End Preloader-->

<div class="wrapper">
    @include('layout.left-sidebar')

    <div class="content-page">
        <div class="content">
            @include('layout.header')

            <div class="container-fluid">
                @yield('content')
            </div>
        </div>

        @include('layout.footer')
    </div>


</div>


<script src="{{asset('assets/js/vendor.min.js')}}"></script>
<script src="{{asset('assets/js/app.min.js')}}"></script>


@yield('more_script')

</body>
</html>